### ISSUE TITLE
Newer versions of cbmconvert are available

### ISSUE THREAD

**Issue by Rhialto** [dansanderson/mega65-welcome-guide#2]
Hi! 

Marko Mäkelä, the author of cbmconvert, has started working on it again. Newer versions are currently available from https://github.com/dr-m/cbmconvert . Current is version 2.1.5.
It is mentioned on page https://dansanderson.com/mega65/welcome/using-disks.html .

**Comment by dansanderson** [comment]
Updated, thanks!
